version: '3'
services:
  client:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    image: vladpustovit/netflix-c-backend:1.0.0
    ports:
      - "8181:8181"
    environment:
      - DB_URL=mongodb+srv://loodi181:Khalidali181@cluster0.kkj1cus.mongodb.net/netflix-app?retryWrites=true&w=majority
      - PORT=8181
      - JWT_KEY=TeamG
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      context: ./nginx-main
      dockerfile: Dockerfile
    ports:
      - "9090:80"